### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by idibidiart** [snuspl/parallax#16]
Hi,

I'd like to try using this. Seems really nice. I have a question (please note I'm new to TensorFlow)

I have N machines, each with one GPU, M Gigabytes of disk storage and J Gigabytes of memory, and my training dataset is accessible to all machines. How do I configure things so that when training in async data parallel mode (PS option) I can make sure only M and J Gigabytes are used per machine? So I can avoid any memory errors. 

Could you setup a Google Groups for this project so we may ask these kinds of questions there?

Thank you!

**Comment by bgchun** [comment]
@idibidiart We have a google groups: parallax-dev@googlegroups.com. Thanks!

**Comment by idibidiart** [comment]
Great! I’ll email any questions that come up and I’ll see you there! Thank you!
