### ISSUE TITLE
Failed to build single device graph in quick start doc

### ISSUE THREAD

**Issue by seojangho** [snuspl/parallax#19]
### Things to Change

'Single Device Graph' example in [Quick Start](https://github.com/snuspl/parallax/blob/master/doc/quick_start.md) may need a modification.

Maybe `with single_device_graph.as_default_graph():` in line 4 should be changed to `with single_device_graph.as_default():`?

### Current Behavior

Running the graph code results in the following error:

```
Traceback (most recent call last):
  File "graph.py", line 4, in <module>
    with single_device_graph.as_default_graph():
AttributeError: 'Graph' object has no attribute 'as_default_graph'
```

### Expected Behavior

No error is expected, as it should build a valid TensorFlow graph.

### How to Reproduce

Execute the given python code using CPyhton 2.7.12 interpreter.

### Related Issues

N/A

**Comment by Danielyijun** [comment]
Hi, do you have any idea how to run Single Device Graph? Thank you.

**Comment by sj6077** [comment]
The typo is fixed.

**Comment by sj6077** [comment]
@Danielyijun you can set only one GPU for "Resource Information" in [Quick Start](https://github.com/snuspl/parallax/blob/master/doc/quick_start.md).

For example, if you write `localhost:0`  to the resource information file, the code runs on the first GPU on your local machine.
